apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
    name: $SERVICIO-router
spec:
    hosts:
        - $HOST
    gateways:
        - apis/api-gateway
    http:
        - match:
              - uri:
                    prefix: /prueba
          route:
              - destination:
                    host: $SERVICIO
                    port:
                        number: 8080
