apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../base/deployment.yml
    - ../base/service.yml
    - ../base/hpa.yml
    - ../base/virtual-service.yml

patchesStrategicMerge:
  - ./change_replicas.yaml